AllCops:
  Exclude:
  - 'bin/**/*'
  - 'db/schema.rb'
  - 'vendor/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.6.5
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 150
Metrics/AbcSize:
  Max: 63
Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 120
Metrics/PerceivedComplexity:
  Max: 12
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/BlockLength:
  Max: 36
Style/NumericLiterals:
  MinDigits: 7
Style/AsciiComments:
  Enabled: No
Style/SignalException:
  Enabled: No
Style/GlobalVars:
  AllowedVariables: [$redis]
Style/ClassAndModuleChildren:
  Enabled: No
Style/FrozenStringLiteralComment:
  Enabled: No
Style/StringLiterals:
  Enabled: No
Layout/ExtraSpacing:
  Exclude:
    - 'config/**/*'
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/**/*'
Layout/SpaceAroundOperators:
  Exclude:
    - 'config/**/*'
Layout/EmptyLines:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
